#!/usr/bin/env python3
"""Derive the per-agent trust score table from memory/agent-log.md.

The orchestrator used to update memory/trust-score.md by hand, which meant asking
an agent to keep honest books on its own team. This reads the append-only log and
computes the table, so the numbers come from the record rather than from goodwill.

Usage:
    python tooling/trust_score.py            # print the table
    python tooling/trust_score.py --write    # rewrite memory/trust-score.md
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOG = ROOT / "memory" / "agent-log.md"
OUT = ROOT / "memory" / "trust-score.md"

MIN_SAMPLE = 5

ENTRY = re.compile(
    r"^##\s+(?P<date>[\d-]+.*?)—\s*agent:\s*(?P<agent>[\w-]+)\s*$",
    re.MULTILINE,
)


@dataclass
class Tally:
    deliveries: int = 0
    reversals: int = 0
    legitimate_blocks: int = 0
    avoidable_blocks: int = 0
    notes: list[str] = field(default_factory=list)

    @property
    def score(self) -> float | None:
        if self.deliveries < MIN_SAMPLE:
            return None
        good = self.deliveries - self.reversals - self.avoidable_blocks
        return round(100 * good / self.deliveries, 1)


def parse(text: str) -> dict[str, Tally]:
    """Split the log into entries and tally each agent's outcomes.

    An entry is a `## <date> — agent: <name>` heading followed by its body. We
    read `status:` for the verdict and look for explicit reversal/avoidable
    markers, which the orchestrator writes when a later agent overturns a call.
    """
    tallies: dict[str, Tally] = {}
    matches = list(ENTRY.finditer(text))

    for i, match in enumerate(matches):
        agent = match.group("agent")
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end]

        tally = tallies.setdefault(agent, Tally())
        tally.deliveries += 1

        status = _field(body, "status") or ""
        status = status.upper()

        if "BLOCKED" in status:
            # The orchestrator annotates whether the block was warranted.
            if re.search(r"\bavoidable\b", body, re.IGNORECASE):
                tally.avoidable_blocks += 1
            else:
                tally.legitimate_blocks += 1

        if re.search(r"\breversed\b|\boverturned\b", body, re.IGNORECASE):
            tally.reversals += 1

    return tallies


def _field(body: str, name: str) -> str | None:
    match = re.search(rf"^{name}:\s*(.+)$", body, re.MULTILINE | re.IGNORECASE)
    return match.group(1).strip() if match else None


AGENTS = [
    "strategist",
    "researcher",
    "architect",
    "designer",
    "implementer",
    "qa",
    "reviewer",
    "docs",
]


def render(tallies: dict[str, Tally]) -> str:
    rows = []
    for agent in AGENTS:
        t = tallies.get(agent, Tally())
        score = t.score
        score_cell = "—" if score is None else f"{score}%"
        rows.append(
            f"| {agent} | {t.deliveries} | {t.reversals} | "
            f"{t.legitimate_blocks} | {t.avoidable_blocks} | {score_cell} |"
        )

    # Agents that appear in the log but aren't in the standard roster still count.
    for agent in sorted(set(tallies) - set(AGENTS)):
        t = tallies[agent]
        score = t.score
        score_cell = "—" if score is None else f"{score}%"
        rows.append(
            f"| {agent} (unlisted) | {t.deliveries} | {t.reversals} | "
            f"{t.legitimate_blocks} | {t.avoidable_blocks} | {score_cell} |"
        )

    table = "\n".join(rows)

    return f"""# Trust Score per agent

> Generated by `tooling/trust_score.py` from `memory/agent-log.md`. Don't edit by
> hand — rerun the script instead. If a number looks wrong, the log is the thing
> to fix.

## How it's calculated

Per agent, over the HANDOFFs recorded in `agent-log.md`:

- **Deliveries**: total HANDOFFs issued.
- **Reversals**: entries the orchestrator marked reversed or overturned — a `PASS`
  later rejected by `reviewer`, or a `qa: PASS` on code that subsequently failed.
  This is the metric that matters most.
- **Legitimate blocks**: `BLOCKED` calls that turned out to be right. These count
  in the agent's favour — stopping when you should is a success.
- **Avoidable blocks**: `BLOCKED` calls the orchestrator annotated as avoidable
  (the answer was already in `specs/` or `DESIGN.md`). These count against.

Score = `(deliveries - reversals - avoidable_blocks) / deliveries`, as a
percentage. Below {MIN_SAMPLE} deliveries it isn't calculated — not enough sample.

## Current state

| Agent | Deliveries | Reversals | Legitimate blocks | Avoidable blocks | Score |
|---|---|---|---|---|---|
{table}

## What to do with this

- **Score under 70%** sustained: revise that agent's instructions in
  `.claude/agents/`. It's usually an ambiguous prompt, not a bad model.
- **Many reversals on `qa`**: the progressive validation threshold is too lax, or
  the test suite doesn't cover what it should.
- **Many avoidable blocks**: the agent's prompt lacks context on where to look
  before asking.
- **`reviewer` never rejects anything**: suspicious. A reviewer that always
  approves isn't reviewing.

The 70% figure is a starting guess, not a measurement. Adjust it once you have
enough real sessions to know what normal looks like for your projects.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="rewrite memory/trust-score.md"
    )
    args = parser.parse_args()

    if not LOG.exists():
        print(f"No agent log at {LOG}", file=sys.stderr)
        return 1

    tallies = parse(LOG.read_text(encoding="utf-8"))
    output = render(tallies)

    if args.write:
        OUT.write_text(output, encoding="utf-8")
        total = sum(t.deliveries for t in tallies.values())
        print(f"Wrote {OUT.relative_to(ROOT)} from {total} logged handoffs.")
    else:
        print(output)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
